# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
print(np.__version__)
np.show_config()

1.20.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Intel/anaconda3/envs/d2l\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Intel/anaconda3/envs/d2l\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Intel/anaconda3/envs/d2l\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Intel/anaconda3/envs/d2l\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Intel/anaconda3/envs/d2l\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Intel/anaconda3/envs/d2l\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Intel/anaconda3/envs/d2l\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Intel/anaconda3/en

#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
Z = np.zeros(10)
Z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆)

In [10]:
Z = np.zeros((10, 10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [13]:
Z = np.zeros(19)
Z[4] = 1
Z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [14]:
Z = np.arange(10, 49)
Z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [17]:
Z = np.arange(10)
Z = Z[::-1]
Z

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [21]:
Z = np.arange(9).reshape(3,3)
Z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [23]:
Z = np.array([1,2,0,0,4,0])
nz = np.nonzero(Z)
nz

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [24]:
Z = np.eye(3)
Z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [27]:
Z = np.random.random((3,3,3))
Z

array([[[0.14676692, 0.13368648, 0.65252342],
        [0.11174956, 0.07310872, 0.35913475],
        [0.85384101, 0.61923893, 0.93483465]],

       [[0.47676058, 0.8321211 , 0.75441111],
        [0.83636074, 0.01745983, 0.83826711],
        [0.71453395, 0.83446284, 0.19563439]],

       [[0.64086218, 0.21068743, 0.93862169],
        [0.17063823, 0.09361183, 0.00413235],
        [0.49610731, 0.84631862, 0.17518071]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [29]:
Z = np.random.random((10, 10))
Z.min(), Z.max()

(0.0037825450341840705, 0.9821306558747736)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [32]:
Z = np.random.random(30)
Z.mean()

0.5647109530954612

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [37]:
Z = np.ones((5, 5))
Z[1:-1, 1:-1] = 0
Z

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [42]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1,mode='constant', constant_values = 0)
Z

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [45]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [48]:
Z = np.diag(np.arange(1, 5), k=-1)
Z

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [51]:
Z = np.zeros((8, 8), dtype=int)
Z[1::2, 0::2] = 1
Z[0::2, 1::2] = 1
Z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [63]:
Z = np.arange(6*7*8).reshape((6, 7, 8))
idx = np.unravel_index(100, (6,7,8))
Z[idx]

100

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [65]:
Z = np.tile(np.array([[0,1],[1,0]]), (4,4))
Z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [85]:
Z = np.random.random((5,5))
Z = (Z - np.mean(Z)) / np.std(Z)
Z

array([[ 0.15852462, -0.50930823,  0.60355038, -0.31226893,  0.07807339],
       [ 0.39086016,  1.48846057,  0.38320368,  1.37270329, -0.52293527],
       [-0.0528155 ,  0.81333127,  0.82395586, -0.86526724, -1.68103317],
       [-1.85195395,  1.72229978, -1.43817452,  0.62775057, -0.50795246],
       [ 1.00498298,  0.49168128,  0.5044809 , -1.76675538, -0.95539408]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [89]:
color = np.dtype([
    ("r", np.ubyte, (1,)),
    ("g", np.ubyte, (1,)),
    ("b", np.ubyte, (1,)),
    ("a", np.ubyte, (1,))
])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [92]:
A = np.random.random((5,3))
B = np.random.random((3,2))
np.matmul(A, B), A@B

(array([[0.68254432, 0.71791701],
        [0.47452066, 0.36722097],
        [0.80065469, 1.14300714],
        [0.5724138 , 0.70035701],
        [0.33577554, 0.36641307]]),
 array([[0.68254432, 0.71791701],
        [0.47452066, 0.36722097],
        [0.80065469, 1.14300714],
        [0.5724138 , 0.70035701],
        [0.33577554, 0.36641307]]))

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [100]:
Z = np.arange(11)
Z[(Z>=3) & (Z<=8)] *= -1
Z

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [103]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [4]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


<ipython-input-4-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-4-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [10]:
Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))
print(Z)

[ 6. 10. -6.  4. -9.  5.  7. -8.  7.  5.]
[ 5.68578287  9.1555398  -5.70337146  3.92419585 -8.38138564  4.36056957
  6.81815686 -7.99767286  6.42317167  4.20927984]


#### 30. How to find common values between two arrays? (★☆☆)

In [11]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))
print(Z1)
print(Z2)

[0 1 5 7 9]
[9 9 6 7 1 0 5 4 5 5]
[3 9 5 5 0 1 9 8 7 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [15]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# An equivalent way, with a context manager:

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [20]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-20-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [21]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [22]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [23]:
A = np.ones(5)
B = np.ones(5)
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1., -1., -1., -1., -1.])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [28]:
Z = np.random.uniform(0,10,5)
print(Z)
print(Z.astype(int))
print(Z - Z%1)
print(np.ceil(Z))
print(np.floor(Z))
print(np.trunc(Z))

[8.09660343 1.58821286 0.93867971 2.90399178 2.04385066]
[8 1 0 2 2]
[8. 1. 0. 2. 2.]
[9. 2. 1. 3. 3.]
[8. 1. 0. 2. 2.]
[8. 1. 0. 2. 2.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [29]:
Z = np.zeros((5, 5))
Z += np.arange(5)
Z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [34]:
def generator():
    for x in range(15):
        yield x 
Z = np.fromiter(generator(), dtype = float, count=10)
Z

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [62]:
Z = np.linspace(0, 1, 11 ,endpoint=False)[1:]
Z

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [38]:
Z = np.random.random(10)
Z.sort()
Z

array([0.09092101, 0.09387706, 0.10990022, 0.21490018, 0.26405883,
       0.62168101, 0.6488065 , 0.9270372 , 0.92859652, 0.97298197])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [39]:
Z = np.arange(10)
np.add.reduce(Z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [48]:
A = np.random.randint(0,2,2)
B = np.random.randint(0,2,2)
print(A)
print(B)
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

[1 1]
[1 1]
True
True


#### 43. Make an array immutable (read-only) (★★☆)

In [49]:
Z = np.zeros(10)
Z.flags.writable = False
Z[0] = 1

AttributeError: 'numpy.flagsobj' object has no attribute 'writable'

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [54]:
Z = np.random.random((10, 2))
X = Z[:,0]
Y = Z[:,1]
R = np.sqrt(X**2 + Y**2)
T = np.arctan2(X, Y)
print(R)
print(T)

[0.38238155 1.03087281 0.96622016 0.94091864 0.69406548 0.84450908
 0.93638182 0.97895489 0.96432343 0.5246534 ]
[1.01876695 1.2911464  0.0929656  1.11445817 0.01930887 1.12546897
 1.31282454 0.23206742 0.62945895 0.61193402]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [55]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.59692106 0.27616193 0.34162578 0.3332093  0.24539408 0.06104997
 0.25144483 0.39937892 0.         0.24212814]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [59]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [65]:
X = np.random.random(5)
Y = np.random.random(4)
C = 1.0 / np.subtract.outer(X,Y)
C

array([[10.12989122, -1.78498081, 15.74997004, -3.05233508],
       [ 2.19811795, -4.90164323,  2.38260272, 34.96641856],
       [ 5.76606562, -2.05965004,  7.23573704, -3.95401808],
       [ 1.21271743,  6.0369507 ,  1.26683491,  2.51093118],
       [ 1.26471739,  7.59055763,  1.32368819,  2.74457821]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [66]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [77]:
import sys
np.set_printoptions(threshold=sys.maxsize)
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [79]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

16


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [82]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-82-6f1aa4d7a2ff>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [93]:
Z = np.random.random((5,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.57245081 0.78469829 0.68652713 0.47900558]
 [0.57245081 0.         0.60637628 0.32445868 0.90079885]
 [0.78469829 0.60637628 0.         0.93082084 1.25693376]
 [0.68652713 0.32445868 0.93082084 0.         0.83427085]
 [0.47900558 0.90079885 1.25693376 0.83427085 0.        ]]


ModuleNotFoundError: No module named 'scipy'

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [97]:
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [99]:
from io import StringIO

# Fake file 
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [106]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [114]:
X, Y = np.meshgrid(np.linspace(-1,1,5), np.linspace(-1,1,5))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.53526143 0.60653066 0.53526143 0.36787944]
 [0.53526143 0.77880078 0.8824969  0.77880078 0.53526143]
 [0.60653066 0.8824969  1.         0.8824969  0.60653066]
 [0.53526143 0.77880078 0.8824969  0.77880078 0.53526143]
 [0.36787944 0.53526143 0.60653066 0.53526143 0.36787944]]


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [117]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [121]:
X = np.random.random((5, 5))
# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)
Y

array([[-0.07640633,  0.03132172, -0.34759701,  0.25667128,  0.13601033],
       [-0.27831688,  0.40879348,  0.15309796, -0.17197533, -0.11159924],
       [-0.43164422,  0.45845375, -0.10891723,  0.41247086, -0.33036315],
       [ 0.09016539,  0.38887884, -0.002595  , -0.41155586, -0.06489337],
       [ 0.00871808,  0.08586291, -0.19936826,  0.03435612,  0.07043116]])

#### 59. How to sort an array by the nth column? (★★☆)

In [130]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[2 8 4]
 [6 5 1]
 [4 5 0]]
[[6 5 1]
 [4 5 0]
 [2 8 4]]


#### 60. How to tell if a given 2D array has zero columns? (★★☆)

In [143]:
Z = np.random.randint(0,3,(3,10))
print(Z)
print((~Z.any(axis=0)).any())

[[0 1 0 0 2 1 1 2 0 0]
 [1 2 0 1 2 0 2 0 1 1]
 [0 2 2 2 0 1 1 1 1 2]]
False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [150]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5181237619936184


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [151]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [157]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [161]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
# Author: Bartosz Telenczuk
np.add.at(Z, I, 1)
print(Z)

[5. 3. 3. 2. 3. 3. 1. 2. 5. 3.]
[9. 5. 5. 3. 5. 5. 1. 3. 9. 5.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [164]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [191]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
#Note that we should compute 256*256 first. 
#Otherwise numpy will only promote F.dtype to 'uint16' and overfolw will occur
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [198]:
A = np.arange(4*3*3*4).reshape((4,3,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
res = A.sum(axis=(-2,-1))
print(res)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[  66  210  354]
 [ 498  642  786]
 [ 930 1074 1218]
 [1362 1506 1650]]
[[  66  210  354]
 [ 498  642  786]
 [ 930 1074 1218]
 [1362 1506 1650]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [216]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)

D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)
# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.4594029  0.46923313 0.44199067 0.6115692  0.55931836 0.62649881
 0.63641015 0.4587524  0.50411848 0.54950046]
0    0.459403
1    0.469233
2    0.441991
3    0.611569
4    0.559318
5    0.626499
6    0.636410
7    0.458752
8    0.504118
9    0.549500
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)

In [229]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version  
# 矩阵乘法，取对角线元素
np.diag(np.dot(A, B))

# Fast version
# 转置后对应元素相乘，降维求和
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([0.56457063, 1.33195165, 1.38847601, 0.76825759, 0.61465185])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)